In [1]:
import pandas as pd

In [2]:
results_er = pd.read_csv("results/param_sweeps/sweep_trials_er.csv")
results_ws = pd.read_csv("results/param_sweeps/sweep_trials_ws.csv")
results_ba = pd.read_csv("results/param_sweeps/sweep_trials_ba.csv")

In [7]:
print("Results ER:")
print('Total number of trials: ' + str(len(results_er)))
# find rows with the maximum best_score (handles ties)
max_score = results_er['best_score'].max()
top_rows = results_er[results_er['best_score'] == max_score]
display(top_rows)
print("Results WS:")    
print('Total number of trials: ' + str(len(results_ws)))
# find rows with the maximum best_score (handles ties)
max_score = results_ws['best_score'].max()
top_rows = results_ws[results_ws['best_score'] == max_score]
display(top_rows)

print("Results BA:")
print('Total number of trials: ' + str(len(results_ba)))
# find rows with the maximum best_score (handles ties)
max_score = results_ba['best_score'].max()
top_rows = results_ba[results_ba['best_score'] == max_score]
display(top_rows)

Results ER:
Total number of trials: 1250

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
193,0.2,5,0.9,0.2,1,12717,-113913.833278,51.522454,NaN

Results WS:
Total number of trials: 1250

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
433,0.3,5,0.9,0.1,0,13348,-72054.254238,38.793239,NaN

Results BA:
Total number of trials: 1250

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,repeat,seed,best_score,elapsed_sec,error
183,0.2,5,0.9,0.1,0,14631,-59470.029273,41.840509,NaN

In [12]:
# find rows with the maximum best_score (handles ties)
max_score = results['best_score'].max()
top_rows = results[results['best_score'] == max_score]
display(top_rows)

,crossover_proportion,crossover_edges,mutation_prob,elitism_proportion,max_parents,connect_disconnected,repeat,seed,best_score,n_nodes,n_edges,in_degree_max,out_degree_max,elapsed_sec,error
379,0.2,2,1.0,0.3,NaN,True,1,19419,-79689.857127,20,42,4,7,184.37308,NaN