In [1]:
import os
from tqdm import tqdm
import sys
if not hasattr(sys.modules[__name__], "cwd_changed"):
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__name__))))
    sys.modules[__name__].cwd_changed = True

import warnings 
warnings.filterwarnings("ignore")
import logging
logging.getLogger('pgmpy').setLevel(logging.WARNING)


import pandas as pd
from utils.graph import dag_to_cpdag
# from metrics.graph import compare_dags
from utils.results import *
from analyses.helpers import load_results

In [2]:

from __future__ import annotations

import os
import hashlib
from typing import Any, Dict, Iterable, List, Optional, Tuple
import pandas as pd
from synthetic.structure import *
from metrics.synergy import find_synergistic_triplets
from synthetic.binary import *
from idtxl.data import Data
from idtxl.bivariate_pid import BivariatePID

def broja_synergy(df, source1, source2, target):

    s1, _ = pd.factorize(df[source1], sort=True)
    s2, _ = pd.factorize(df[source2], sort=True)
    t,  _ = pd.factorize(df[target], sort=True)

    data = Data(np.vstack((s1, s2, t)), 'ps', normalise=False)

    settings = {
        'alpha': 0.1,
        'alph_s1': int(s1.max() + 1),
        'alph_s2': int(s2.max() + 1),
        'alph_t': int(t.max() + 1),
        'max_unsuc_swaps_row_parm': 60,
        'num_reps': 63,
        'max_iters': 1000,
        'pid_estimator': 'TartuPID',
        'verbose': False,
        'lags_pid': [0, 0],   # or remove if you do not want lagged PID
    }

    pid_analysis = BivariatePID()
    results = pid_analysis.analyse_single_target(
        settings=settings,
        data=data,
        target=2,
        sources=[0, 1],
    )
    return results.get_single_target(2)['syn_s1_s2']

def evaluate_triplet(df, triplet):
    highest_pid = 0

    triplet = list(map(str, triplet))

    for col in triplet:
        target = col
        source1, source2 = [c for c in triplet if c != target]
        pid = broja_synergy(df, source1, source2, target)
        # print(f"Evaluating triplet {source1}, {source2} -> {target}: PID = {pid}")

        if pid > highest_pid:
            highest_pid = pid
            final_triplet = (source1, source2, target)

    # print(final_triplet)
    # print(f"\nHighest PID for triplet {final_triplet}: {highest_pid} with target {final_triplet[2]}\n")
    return (final_triplet, highest_pid)

In [16]:
n_nodes = 20
n_samples = 10_000
fam = "ER"
dag, topo, info = sample_dag_family_with_caps(
n_nodes=n_nodes,
family=fam,
# seed=structure_seed,
max_indeg=int(2),
max_outdeg=int(2),
)

p_syn=1
sharpness=12

node_cpd, cpd_info = build_node_cpds_from_dag(
    dag,
    topo=topo,
    # seed_params=seed_params,
    # root_p=float(root_p),
    # p_copy_flip=float(p_copy_flip),
    p_syn=float(p_syn),
    sharpness=float(sharpness),
)
df, dag_str, node_spec, meta = simulate_from_dag_cpds(
                            dag,
                            node_cpd,
                            n_samples=n_samples,
                            p_flip_global=0,
                            topo=topo,
                        )

In [17]:
ii_triplets = find_synergistic_triplets(df)

In [18]:
meta

          Combs      Type
0        [1, 3]  Pairwise
1        [0, 4]  Pairwise
2        [3, 9]  Pairwise
3    [0, 3, 12]       XOR
4    [5, 7, 13]       XOR
5       [2, 14]  Pairwise
6       [7, 15]  Pairwise
7   [6, 10, 16]       XOR
8      [11, 17]  Pairwise
9      [10, 18]  Pairwise
10   [2, 6, 19]       XOR

In [20]:
from joblib import Parallel, delayed
results = Parallel(n_jobs=10, backend="loky")(
            delayed(evaluate_triplet)(df, triplet) for triplet in ii_triplets
        )
    
count = 0
for i in results:
    triplet_i = i[0]
    pid_i = i[1]
    print(f"Triplet: {i[0]} with PID {i[1]}")
    if int(triplet_i[2]) > int(triplet_i[0]) and int(triplet_i[2]) > int(triplet_i[1]):
        count += 1

ratio = count / len(results)
print(f"Ratio of triplets where target has higher PID than sources: {ratio:.2f}")

Triplet: ('6', '10', '16') with PID 0.9755098460246805
Triplet: ('2', '6', '19') with PID 0.9747164086317135
Triplet: ('3', '12', '0') with PID 0.9721059460067034
Triplet: ('7', '13', '5') with PID 0.9637728969262926
Triplet: ('6', '14', '19') with PID 0.7245315840351891
Triplet: ('13', '15', '5') with PID 0.715872722201115
Triplet: ('0', '12', '1') with PID 0.7109231350338387
Triplet: ('6', '18', '16') with PID 0.7073765311711839
Triplet: ('4', '12', '3') with PID 0.6942657413395018
Triplet: ('0', '12', '9') with PID 0.6823626597894972
Triplet: ('4', '12', '1') with PID 0.5376405245211094
Triplet: ('4', '12', '9') with PID 0.5116858841003543
Ratio of triplets where target has higher PID than sources: 0.25

## Lower Sharpness

In [ ]:
# n_nodes = 20
# n_samples = 10_000
# p_syn=1
# sharpness=12

# node_cpd, cpd_info = build_node_cpds_from_dag(
#     dag,
#     topo=topo,
#     # seed_params=seed_params,
#     # root_p=float(root_p),
#     # p_copy_flip=float(p_copy_flip),
#     p_syn=float(p_syn),
#     sharpness=float(sharpness),
# )
# df, dag_str, node_spec, meta = simulate_from_dag_cpds(
#                             dag,
#                             node_cpd,
#                             n_samples=n_samples,
#                             p_flip_global=0,
#                             topo=topo,
#                         )

In [15]:
meta

           Combs      Type
0         [0, 4]  Pairwise
1         [3, 6]  Pairwise
2         [4, 8]  Pairwise
3         [8, 9]  Pairwise
4        [3, 12]  Pairwise
5    [2, 12, 14]       XOR
6        [1, 15]  Pairwise
7        [6, 17]  Pairwise
8       [15, 18]  Pairwise
9     [2, 7, 19]       XOR
10      [14, 20]  Pairwise
11      [17, 22]  Pairwise
12      [20, 23]  Pairwise
13      [13, 24]  Pairwise
14   [7, 22, 26]       XOR
15  [16, 26, 27]       XOR
16  [11, 14, 28]       XOR
17       [4, 29]  Pairwise
18       [6, 30]  Pairwise
19  [22, 28, 31]       XOR
20  [11, 29, 32]       XOR
21      [18, 34]  Pairwise
22  [26, 28, 35]       XOR
23  [21, 25, 36]       XOR
24  [10, 13, 37]       XOR
25  [16, 31, 38]       XOR
26  [21, 38, 39]       XOR
27   [5, 10, 40]       XOR
28  [19, 23, 41]       XOR
29  [15, 40, 42]       XOR
30  [36, 41, 43]       XOR
31  [20, 24, 44]       XOR
32   [1, 34, 45]       XOR
33  [24, 37, 46]       XOR
34   [8, 33, 47]       XOR
35  [43, 46, 48]       XOR
36   [0, 27, 49]       XOR

In [13]:
ii_triplets = find_synergistic_triplets(df)

In [14]:
from joblib import Parallel, delayed
results = Parallel(n_jobs=10, backend="loky")(
            delayed(evaluate_triplet)(df, triplet) for triplet in ii_triplets
        )
    
count = 0
for i in results:
    triplet_i = i[0]
    pid_i = i[1]
    print(f"Triplet: {i[0]} with PID {i[1]}")
    if int(triplet_i[2]) > int(triplet_i[0]) and int(triplet_i[2]) > int(triplet_i[1]):
        count += 1

ratio = count / len(results)
print(f"Ratio of triplets where target has higher PID than sources: {ratio:.2f}")

Triplet: ('11', '32', '29') with PID 0.9809583715102597
Triplet: ('2', '12', '14') with PID 0.9789955787497258
Triplet: ('8', '47', '33') with PID 0.9767374199771274
Triplet: ('16', '38', '31') with PID 0.9767370443227409
Triplet: ('15', '40', '42') with PID 0.9764744976457751
Triplet: ('2', '19', '7') with PID 0.9757875474455111
Triplet: ('20', '44', '24') with PID 0.9756898819310986
Triplet: ('37', '46', '24') with PID 0.9753847364643264
Triplet: ('22', '31', '28') with PID 0.9748874766847386
Triplet: ('7', '26', '22') with PID 0.9747963394281077
Triplet: ('26', '35', '28') with PID 0.9748009959416402
Triplet: ('10', '37', '13') with PID 0.9746439090615544
Triplet: ('46', '48', '43') with PID 0.9744982866927504
Triplet: ('27', '49', '0') with PID 0.97390366675202
Triplet: ('38', '39', '21') with PID 0.9737938659507089
Triplet: ('25', '36', '21') with PID 0.9729698791522733
Triplet: ('19', '23', '41') with PID 0.9728720354152108
Triplet: ('36', '41', '43') with PID 0.9699576664994465
Triplet: ('16', '26', '27') with PID 0.9639887534039325
Triplet: ('10', '40', '5') with PID 0.9637369386214011
Triplet: ('11', '14', '28') with PID 0.9577026460627274
Triplet: ('7', '35', '31') with PID 0.9362257246004169
Triplet: ('1', '40', '42') with PID 0.7221301783564287
Triplet: ('20', '44', '13') with PID 0.7198635444092105
Triplet: ('10', '37', '24') with PID 0.7192759589257343
Triplet: ('13', '46', '37') with PID 0.7188916930063606
Triplet: ('2', '12', '20') with PID 0.7092308843649828
Triplet: ('14', '44', '24') with PID 0.7085591305362675
Triplet: ('18', '40', '42') with PID 0.7081426352513649
Triplet: ('2', '3', '14') with PID 0.7064006588826451
Triplet: ('17', '26', '7') with PID 0.7050747823176331
Triplet: ('11', '32', '4') with PID 0.7050452850342596
Triplet: ('23', '44', '24') with PID 0.7049983704740197
Triplet: ('19', '20', '41') with PID 0.7039859998338793
Triplet: ('17', '31', '28') with PID 0.7011838010336879
Triplet: ('10', '48', '43') with PID 0.6995914177530862
Triplet: ('11', '20', '28') with PID 0.6985252335144154
Triplet: ('4', '33', '47') with PID 0.6981831801644042
Triplet: ('40', '46', '5') with PID 0.6949269276872228
Triplet: ('4', '49', '27') with PID 0.6930166785390126
Triplet: ('9', '33', '47') with PID 0.6846043778583479
Triplet: ('14', '44', '13') with PID 0.5551782528942764
Triplet: ('23', '44', '13') with PID 0.5537748803580806
Triplet: ('34', '40', '42') with PID 0.5486303471394898
Triplet: ('2', '12', '23') with PID 0.5476030057079118
Triplet: ('14', '19', '41') with PID 0.5451897112729933
Triplet: ('2', '6', '14') with PID 0.5451571709342962
Triplet: ('2', '3', '20') with PID 0.543497281693543
Triplet: ('11', '23', '28') with PID 0.541258394403851
Triplet: ('11', '32', '0') with PID 0.5372307147902953
Ratio of triplets where target has higher PID than sources: 0.40

In [9]:
## Bit-flip Noise

In [21]:

df, dag_str, node_spec, meta = simulate_from_dag_cpds(
                            dag,
                            node_cpd,
                            n_samples=n_samples,
                            p_flip_global=0.3,
                            topo=topo,
                        )
ii_triplets = find_synergistic_triplets(df)

In [23]:
from joblib import Parallel, delayed
results = Parallel(n_jobs=10, backend="loky")(
            delayed(evaluate_triplet)(df, triplet) for triplet in ii_triplets
        )
    
count = 0
for i in results:
    triplet_i = i[0]
    pid_i = i[1]
    print(f"Triplet: {i[0]} with PID {i[1]}")
    if int(triplet_i[2]) > int(triplet_i[0]) and int(triplet_i[2]) > int(triplet_i[1]):
        count += 1

ratio = count / len(results)
print(f"Ratio of triplets where target has higher PID than sources: {ratio:.2f}")

Triplet: ('6', '19', '2') with PID 0.12432603259973474
Triplet: ('3', '12', '0') with PID 0.11900752693842298
Triplet: ('6', '16', '10') with PID 0.11854772385579615
Triplet: ('5', '13', '7') with PID 0.10875568607944242
Ratio of triplets where target has higher PID than sources: 0.00